--1

SELECT *FROM deposit

--2
SELECT *FROM Borrow

--3
SELECT *FROM Customers

--4
SELECT ACTNO, CNAME, AMOUNT FROM deposit

--5
SELECT LOANNO, AMOUNT FROM Borrow

--6
SELECT *FROM Borrow
WHERE BNAME='ANDHERI'

--7
SELECT ACTNO, AMOUNT FROM deposit
WHERE ACTNO=106

--8
SELECT CNAME FROM Borrow
WHERE AMOUNT>5000

--9
SELECT CNAME FROM deposit
WHERE ADATE>='1996-12-1'

--10
SELECT CNAME FROM deposit
WHERE ACTNO<105

--11
SELECT CNAME FROM Customers
WHERE CITY='NAGPUR' OR CITY='DELHI'

--12
SELECT CNAME, BNAME FROM deposit
WHERE AMOUNT>4000 AND ACTNO<105

--13
SELECT CNAME FROM Borrow
WHERE AMOUNT>=3000 OR AMOUNT<=8000

--14
SELECT CNAME FROM deposit
WHERE NOT BNAME='ANDHERI'

--15
SELECT ACTNO, CNAME, AMOUNT FROM deposit
WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104

--B

--1
SELECT TOP 5 CNAME FROM deposit

--2
SELECT TOP 3 CNAME, AMOUNT FROM deposit WHERE AMOUNT>1000

--3
SELECT TOP 5 LOANNO, CNAME FROM BORROW WHERE BNAME<>'ANDHERI'

--4
SELECT DISTINCT CITY FROM Customers

--5
SELECT DISTINCT BNAME FROM Branch

--C

--1
SELECT TOP 50 PERCENT *FROM Borrow

--2
SELECT TOP 10 PERCENT *FROM deposit

--3
SELECT TOP 25 PERCENT *FROM CNAME 